---
title: UniekLee
baseURL: "/"
params:
  layout_style: overflow
  palette: green
  header:
    title: UniekLee
    tagline: There's only one Lee like me
    profile_img: "/images/2020/04/Lee_EngagementShoot_Colour copy.jpg"
    bg: dark
    has_nav: true
    has_social: true
  footer:
    content: "&copy; All rights reserved."
    links:
    - text: Made with Stackbit
      url: https://www.stackbit.com
      new_window: true
disableKinds:
- RSS
- taxonomy
- taxonomyTerm
